{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "docmost.name" . }}-postgres
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "docmost.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "docmost.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  clusterIP: None
{{- end }}
