{{- if .Values.secrets.createFromValues }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docmost.name" . }}-app-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.app.dbPassword | b64enc }}
  APP_SECRET: {{ .Values.secrets.app.appSecret | b64enc }}
  TELEGRAM_BOT_TOKEN: {{ .Values.secrets.app.telegramBotToken | b64enc }}
  TELEGRAM_CHAT_ID: {{ .Values.secrets.app.telegramChatId | toString | b64enc }}
  GRAFANA_PASSWORD: {{ .Values.secrets.app.grafanaPassword | b64enc }}
{{- end }}
