{{- if and .Values.secrets.createFromValues .Values.monitoring.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docmost.name" . }}-grafana-admin-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  admin-password: {{ .Values.secrets.app.grafanaPassword | quote }}
{{- end }}
