{{- if and .Values.monitoring.enabled .Values.monitoring.alertmanager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docmost.name" . }}-alertmanager-config
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'severity']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'telegram'
    receivers:
    - name: 'telegram'
      telegram_configs:
      - bot_token: {{ .Values.monitoring.alertmanager.telegram.botToken | quote }}
        chat_id: {{ .Values.monitoring.alertmanager.telegram.chatId | int }}
        message: '{{`{{ template "telegram.message" . }}`}}'
        parse_mode: HTML
        disable_notifications: false
    templates:
    - '/etc/alertmanager/templates/*.tmpl'
{{- end }}
