{{- if and .Values.monitoring.enabled .Values.monitoring.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docmost.name" . }}-grafana-provisioning
  namespace: {{ .Values.global.namespace }}
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://{{ include "docmost.name" . }}-prometheus:9090
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        url: http://{{ include "docmost.name" . }}-loki:3100
        access: proxy
  dashboards.yml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
{{- end }}
