apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: docmost
data:
  config.alloy: |
    local.file_match "k8s_logs" {
      path_targets = [
        {
          __path__ = "/var/log/containers/*.log",
        },
      ]
    }
    loki.source.file "collect" {
      targets    = local.file_match.k8s_logs.targets
      forward_to = [loki.process.parser.receiver]
    }
    loki.process "parser" {
      stage.cri {}
      stage.regex {
        expression = "^(?P<time>[^ ]+) (?P<stream>stdout|stderr) (?P<log>.*)$"
      }
      stage.labels {
        values = {
          stream = "",
        }
      }
      stage.timestamp {
        source = "time"
        format = "RFC3339Nano"
      }
      stage.output {
        source = "log"
      }
      forward_to = [loki.write.default.receiver]
    }
    loki.write "default" {
      endpoint {
        url = "http://loki:3100/loki/api/v1/push"
      }
    }
