Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.ssh.insert_key = false

  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 2048
    libvirt.cpus = 2
    libvirt.disk_bus = "virtio"
    libvirt.nested = true
    libvirt.management_network_address = "192.168.123.0/24"
  end

  nodes = {
    "docmost-k3s-server" => "192.168.123.214",
    "docmost-k3s-agent1" => "192.168.123.132",
    "docmost-k3s-agent2" => "192.168.123.203"
  }

  nodes.each do |name, ip|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network :private_network, ip: ip

      node.vm.synced_folder ".", "/vagrant", disabled: true

      node.vm.provision "shell", inline: <<-SHELL
        set -e
        apt-get update
        apt-get upgrade -y
        apt-get install -y curl vim git rsync openssh-server
      SHELL
    end
  end
end
