k3s_version: "v1.33.1+k3s1"
k3s_token: "06b1088abf9ec8f780e9f6d3910804137936907a886ef4821a717cd30b7bbd26"
k3s_server_ip: "{{ hostvars[groups['k3s_server'][0]]['ansible_host'] }}"

ansible_user: vagrant
ansible_python_interpreter: /usr/bin/python3

vagrant_ssh_key: "{{ lookup('env', 'HOME') }}/.vagrant.d/insecure_private_key"

ansible_ssh_private_key_file: "{{ vagrant_ssh_key }}"
runner_ssh_key: "{{ vagrant_ssh_key }}"
runner_user: "{{ ansible_user }}"
runner_host: "{{ hostvars[groups['runners'][0]]['ansible_host'] | default('192.168.123.215') }}"