---
- name: Sync K3s kubeconfig to runner
  hosts: k3s_server
  become: true
  remote_user: vagrant
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml

  tasks:
    - name: Fetch kubeconfig from server
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /tmp/k3s.yaml
        flat: yes

    - name: Fix server address in kubeconfig
      replace:
        path: /tmp/k3s.yaml
        regexp: '127\.0\.0\.1'
        replace: "{{ k3s_server_ip }}"
      delegate_to: localhost
      run_once: true
      become: false

    - name: Create .kube dir and copy config to runner
      delegate_to: localhost
      become: false
      shell: |
        ssh -i {{ runner_ssh_key }} -o StrictHostKeyChecking=no {{ runner_user }}@{{ runner_host }} "mkdir -p /home/{{ runner_user }}/.kube"
        scp -i {{ runner_ssh_key }} -o StrictHostKeyChecking=no \
          /tmp/k3s.yaml \
          {{ runner_user }}@{{ runner_host }}:/home/{{ runner_user }}/.kube/config

    - name: Set correct permissions on runner
      delegate_to: localhost
      become: false
      shell: |
        ssh -i {{ runner_ssh_key }} -o StrictHostKeyChecking=no {{ runner_user }}@{{ runner_host }} "chmod 600 /home/{{ runner_user }}/.kube/config"