{{- if and .Values.monitoring.enabled .Values.monitoring.blackboxExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "docmost.name" . }}-blackbox-exporter
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "docmost.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "docmost.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: blackbox-exporter
  ports:
  - name: http
    port: 9115
    targetPort: 9115
{{- end }}
