{{- if and .Values.monitoring.enabled .Values.monitoring.prometheus.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "docmost.name" . }}-prometheus
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "docmost.labels" . | nindent 4 }}
{{- end }}
